=== hmcts/cpp-context-staging-dvla/stagingdvla-command/stagingdvla-command-api/src/raml/json/schema/stagingdvla.command.driver-notification.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/cpp/stagingdvla/command/driver-notification.json",
  "description": "The details required to generate a now document",
  "type": "object",
  "properties": {
    "masterDefendantId": {
      "description": "The master identifier of the defendant that is the subject of this NOW",
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "orderingCourt": {
      "$ref": "http://justice.gov.uk/core/courts/courtCentre.json"
    },
    "nowContent": {
      "$ref": "#/definitions/nowDocumentContent"
    },
    "orderingHearingId": {
      "description": "The identifier of the hearing that ordered this NOW",
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "isReshare": {
      "type": "boolean"
    }
  },
  "required": [
    "masterDefendantId",
    "orderingCourt",
    "nowContent",
    "orderingHearingId",
    "isReshare"
  ],
  "definitions": {
    "nowDocumentContent": {
      "type": "object",
      "properties": {
        "orderDate": {
          "type": "string",
          "format": "date"
        },
        "amendmentDate": {
          "type": "string",
          "format": "date"
        },
        "defendant": {
          "$ref": "http://justice.gov.uk/core/courts/nowdocument/nowdefendant.json"
        },
        "caseApplicationReferences": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "cases": {
          "title": "cases",
          "type": "array",
          "items": {
            "$ref": "#/definitions/prosecutionCase"
          }
        },
        "courtApplications": {
          "title": "courtApplications",
          "type": "array",
          "items": {
            "$ref": "#/definitions/courtApplication"
          }
        }
      },
      "required": [
        "orderDate",
        "defendant",
        "cases"
      ],
      "additionalProperties": false
    },
    "prosecutionCase": {
      "type": "object",
      "properties": {
        "reference": {
          "type": "string"
        },
        "initiationCode": {
          "type": "string"
        },
        "caseId": {
          "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
        },
        "caseStatus": {
          "type": "string"
        },
        "defendantCaseOffences": {
          "type": "array",
          "title": "defendantCaseOffences",
          "items": {
            "$ref": "#/definitions/defendantCaseOffence"
          }
        }
      },
      "required": [
        "reference",
        "defendantCaseOffences"
      ],
      "additionalProperties": false
    },
    "courtApplication": {
      "type": "object",
      "properties": {
        "applicationReference": {
          "type": "string"
        },
        "applicationStatus": {
          "type": "string"
        },
        "applicationType": {
          "type": "string"
        },
        "applicationTypeId": {
          "type": "string"
        },
        "applicationCode": {
          "type": "string"
        },
        "applicationReceivedDate": {
          "type": "string",
          "format": "date"
        },
        "id": {
          "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
        },
        "results": {
          "type": "array",
          "title": "results",
          "items": {
            "$ref": "#/definitions/result"
          }
        }
      },
      "required": [
        "applicationReference",
        "id"
      ],
      "additionalProperties": false
    },
    "defendantCaseOffence": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "civilOffence": {
          "description": "Indicates that the offence is a civil matter rather than a criminal one",
          "type": "boolean"
        },
        "startDate": {
          "description": "The start date of the offence",
          "type": "string",
          "format": "date"
        },
        "endDate": {
          "description": "The end date of the offence",
          "type": "string",
          "format": "date"
        },
        "convictionDate": {
          "description": "Indicates that prosecution of this offence has led to a criminal conviction.  Not relevant for civil cases",
          "type": "string"
        },
        "convictingCourtCode": {
          "description": "Indicates the code of Convicting court when that prosecution of this offence has led to a criminal conviction. Not relevant for civil cases",
          "type": "string"
        },
        "convictionStatus": {
          "description": "Indicates the status of a conviction.  Null when offence is civil.  Not Convicted when there is not a conviction date.  Otherwise Convicted",
          "type": "string"
        },
        "plea": {
          "description": "The plea entered against the offence",
          "type": "string"
        },
        "vehicleRegistration": {
          "description": "The vehicle registration relevant to the offence",
          "type": "string"
        },
        "code": {
          "type": "string"
        },
        "dvlaCode": {
          "description": "The dvla code for the offence e.g. SP50",
          "type": "string"
        },
        "modeOfTrial": {
          "type": "string"
        },
        "allocationDecision": {
          "type": "string"
        },
        "wording": {
          "type": "string"
        },
        "alcoholReadingAmount": {
          "type": "integer"
        },
        "alcoholReadingMethodCode": {
          "type": "string"
        },
        "alcoholReadingMethodDescription": {
          "type": "string"
        },
        "endorsableFlag": {
          "type": "boolean"
        },
        "results": {
          "type": "array",
          "title": "results",
          "items": {
            "$ref": "#/definitions/result"
          }
        }
      },
      "additionalProperties": false
    },
    "result": {
      "type": "object",
      "properties": {
        "label": {
          "type": "string"
        },
        "resultIdentifier": {
          "type": "string"
        },
        "nowRequirementText": {
          "type": "array",
          "description": "A collection of all the now requirement text items for now requirements associated to the given result",
          "title": "nowRequirementTextItems",
          "items": {
            "$ref": "http://justice.gov.uk/core/courts/nowdocument/now-text.json"
          }
        },
        "publishedForNows": {
          "description": "Determines that when this result published it is published for NOWs only and not for LAA, Court Extract & SPI",
          "type": "boolean"
        },
        "prompts": {
          "type": "array",
          "title": "prompts",
          "items": {
            "$ref": "#/definitions/prompt"
          }
        },
        "resultWording": {
          "type": "string"
        },
        "resultDefinitionGroup": {
          "description": "The result definition group for filtering purposes",
          "type": "string"
        },
        "sequence": {
          "type": "number"
        },
        "d20": {
          "description": "Determines that the result is a D20 result",
          "type": "boolean"
        },
        "pointsDisqualificationCode": {
          "type": "string"
        },
        "drivingTestStipulation": {
          "type": "integer"
        },
        "dvlaCode": {
          "type": "string"
        },
        "judicialResultCategory": {
          "$ref": "http://justice.gov.uk/core/courts/courtsDefinitions.json#/definitions/judicialResultCategory"
        }
      },
      "required": [
        "label"
      ],
      "additionalProperties": false
    },
    "prompt": {
      "type": "object",
      "properties": {
        "label": {
          "type": "string"
        },
        "welshLabel": {
          "type": "string"
        },
        "value": {
          "type": "string"
        },
        "welshValue": {
          "type": "string"
        },
        "promptIdentifier": {
          "type": "string"
        },
        "promptReference": {
          "type": "string"
        },
        "durationSequence": {
          "description": "Determines if the prompt is describing the primary, secondary or tertiary duration in the duration element",
          "type": "number",
          "maximum": 9
        }
      },
      "required": [
        "label"
      ],
      "additionalProperties": false
    }
  }
}

=== hmcts/cpp-context-staging-dvla/stagingdvla-integration-test/src/test/resources/appealAmendReshare/cimd_3236_ac4/command2.json
{
  "masterDefendantId": "%DEFENDANT_ID%",
  "orderingCourt": {
    "address": {
      "address1": "176A Lavender Hill",
      "address2": "London",
      "postcode": "SW11 1JU"
    },
    "code": "B01LY00",
    "courtHearingLocation": "B01LY02",
    "id": "f8254db1-1683-483e-afb3-b87fde5a0a26",
    "lja": {
      "ljaCode": "2577",
      "ljaName": "South West London Magistrates' Court"
    },
    "name": "Lavender Hill Magistrates' Court",
    "roomId": "b4562684-9209-3ec4-a544-7f80dabd94d8",
    "roomName": "Courtroom 02"
  },
  "nowContent": {
    "orderDate": "2026-10-27",
    "defendant": {
      "dateOfBirth": "2000-09-09",
      "gender": "MALE",
      "driverNumber": "ABCDE00010BCFAA",
      "title": "MR",
      "firstName": "Liana",
      "middleName": "Jasmine Jasmine",
      "lastName": "Powlowski",
      "name": "Liana Jasmine Jasmine Powlowski",
      "address": {
        "line1": "56saon",
        "line2": "56Police House",
        "line3": "StreetDescription1",
        "line4": "Locality1",
        "line5": "Fayborough",
        "postCode": "TW14 9XJ"
      }
    },
    "caseApplicationReferences": [
      "JW29150867"
    ],
    "cases": [
      {
        "reference": "JW29150867",
        "caseId": "a0738dff-4498-4b4b-95e3-189b1b7e91a2",
        "defendantCaseOffences": [
          {
            "allocationDecision": "Summary-only offence",
            "civilOffence": false,
            "code": "RA88001",
            "convictingCourtCode": "2577",
            "convictionDate": "2026-06-05",
            "convictionStatus": "Convicted",
            "dvlaCode": "IN10",
            "endorsableFlag": true,
            "modeOfTrial": "Summary",
            "plea": "GUILTY",
            "results": [
              {
                "d20": true,
                "label": "Driving record endorsed (no points)",
                "prompts": [],
                "publishedForNows": false,
                "resultIdentifier": "b0aeb4fc-df63-4e2f-af88-97e3f23e847f"
              },
              {
                "resultIdentifier": "c3a39c2f-b056-442f-8dfc-604b5434f956",
                "publishedForNows": true,
                "d20": false,
                "label": "0: None or unknown"
              }
            ],
            "startDate": "2025-12-07",
            "title": "Use a motor vehicle on a road / public place without third party insurance",
            "wording": "Use a motor vehicle on a road / public place without third party insurance"
          },
          {
            "allocationDecision": "Summary-only offence",
            "civilOffence": false,
            "code": "RA88002",
            "convictingCourtCode": "2577",
            "convictionDate": "2026-06-05",
            "convictionStatus": "Convicted",
            "dvlaCode": "IN20",
            "endorsableFlag": true,
            "modeOfTrial": "Summary",
            "plea": "GUILTY",
            "results": [
              {
                "resultIdentifier": "ccfc452e-ebe4-4cd7-b8a0-4f90768447b4",
                "publishedForNows": false,
                "prompts": [
                  {
                    "promptIdentifier": "2bf54447-328c-4c1b-a123-341adbd52172",
                    "promptReference": "disqualificationPeriod",
                    "durationSequence": 1,
                    "label": "Disqualification period",
                    "value": "12 Months"
                  },
                  {
                    "promptIdentifier": "a593ae4a-9d69-45b9-9585-c11aeed28404",
                    "promptReference": "defendantDrivingLicenceNumber",
                    "label": "Defendant driving licence number",
                    "value": "ABCDE00010BCFAA"
                  }
                ],
                "resultWording": "Disqualified for holding or obtaining a driving licence. Discretionary disqualification. Driving record endorsed. Section 34(2) Road Traffic Offenders Act 1988",
                "d20": true,
                "label": "Discretionary with ordinary disqualification"
              },
              {
                "resultIdentifier": "c3a39c2f-b056-442f-8dfc-604b5434f956",
                "publishedForNows": true,
                "d20": false,
                "label": "0: None or unknown"
              }
            ],
            "startDate": "2025-12-07",
            "title": "Drive a motor vehicle otherwise than in accordance with a licence - endorsable offence",
            "wording": "Drive a motor vehicle otherwise than in accordance with a licence - endorsable offence"
          },
          {
            "allocationDecision": "Summary-only offence",
            "civilOffence": false,
            "code": "RA88003",
            "convictingCourtCode": "2577",
            "convictionDate": "2026-06-05",
            "convictionStatus": "Convicted",
            "dvlaCode": "IN30",
            "endorsableFlag": true,
            "modeOfTrial": "Summary",
            "plea": "GUILTY",
            "results": [
              {
                "d20": false,
                "dvlaCode": "E",
                "label": "Offence not dealt with as part of application - original adjudication to stand",
                "prompts": [],
                "publishedForNows": false,
                "resultIdentifier": "3e859586-bc86-407d-bd8e-c9a01d40d147"
              }
            ],
            "startDate": "2025-12-07",
            "title": "Drive motor vehicle fail comply with red / green arrow / lane closure traffic light signals - manual detection",
            "wording": "Has a violent past and fear that he will commit further offences and interfere with witnesse"
          }
        ]
      }
    ],
    "courtApplications": [
      {
        "applicationReceivedDate": "2026-02-05",
        "applicationReference": "SG821225728",
        "applicationStatus": "FINALISED",
        "applicationType": "Appeal against conviction and sentence by a Magistrates' Court to the Crown Court",
        "applicationTypeId": "abc05494-05d7-4289-b4bc-a92726257a4b",
        "id": "922eb0f2-4b94-448b-8c0c-9deb06b82484",
        "results": [
          {
            "d20": false,
            "label": "Appeal against sentence allowed",
            "prompts": [],
            "publishedForNows": false,
            "resultIdentifier": "d861586a-df88-440d-98d4-63cc2a680ae1",
            "resultWording": ""
          }
        ]
      }
    ]
  },
  "isReshare": true,
  "orderingHearingId": "93bc6155-952f-4909-a36a-b9f277da3b85"
}

=== hmcts/cpp-context-staging-dvla/stagingdvla-integration-test/src/test/resources/appealAmendReshare/dd-27008/scenario1/command4.json
{
  "masterDefendantId": "%DEFENDANT_ID%",
  "orderingCourt": {
    "address": {
      "address1": "1 Queen Victoria Street",
      "address2": "London",
      "address3": "",
      "address4": "",
      "address5": "",
      "postcode": "EC4N 4XY"
    },
    "code": "B01DU00",
    "courtHearingLocation": "B01DU02",
    "id": "c133d0de-c989-48b9-bd20-0431943e347e",
    "lja": {
      "ljaCode": "2570",
      "ljaName": "Central London Magistrates' Court"
    },
    "name": "City of London Magistrates' Court",
    "roomId": "6d335b1f-769f-3120-bcda-c5d7c0725d3a",
    "roomName": "Courtroom 02"
  },
  "nowContent": {
    "orderDate": "2024-10-14",
    "defendant": {
      "dateOfBirth": "2000-01-01",
      "gender": "MALE",
      "driverNumber": "ULLRI611187XH9ZM",
      "firstName": "Jillian",
      "lastName": "Pfannerstill",
      "name": "Jillian Pfannerstill",
      "address": {
        "line1": "FLAT - 25A",
        "line2": "55464 Earlene Islands",
        "line3": "Swansea",
        "line4": "Walsh",
        "line5": "UK",
        "postCode": "SA1 1AU"
      }
    },
    "caseApplicationReferences": [
      "DVLA02022364"
    ],
    "cases": [
      {
        "reference": "DVLA02022364",
        "caseId": "ade7da53-fd6b-446f-828f-2bdedfd2be4d",
        "defendantCaseOffences": []
      }
    ],
    "courtApplications": [
      {
        "applicationType": "Appeal against sentence by a Magistrates' Court to the Crown Court",
        "applicationReceivedDate": "2024-10-01",
        "id": "0eb83dff-5cd2-4f81-8ead-f847018d57c3",
        "applicationReference": "DVLA02022364",
        "applicationStatus": "UN_ALLOCATED",
        "results": [
          {
            "resultIdentifier": "2b3f7c20-8fc1-4fad-9076-df196c24b27e",
            "publishedForNows": false,
            "d20": false,
            "label": "Granted"
          },
          {
            "resultIdentifier": "4ad82d44-41cc-4e47-a2f5-e0dd147320ee",
            "publishedForNows": true,
            "d20": true,
            "label": "Driving disqualification stands"
          }
        ]
      }
    ]
  },
  "isReshare": true,
  "orderingHearingId": "e35a5151-986c-417f-ae23-8fc647e9a759"
}

=== hmcts/cpp-context-staging-dvla/stagingdvla-domain/stagingdvla-domain-aggregate/src/test/resources/testdata/drivernotifications/appeal/cimd-3242/ac4/application-resulted.json
{
  "masterDefendantId": "122b1916-dfbd-47d6-a622-39eb4f6ef765",
  "orderingCourt": {
    "address": {
      "address1": "1-15 Pocock Street",
      "address2": "London",
      "address3": "",
      "address4": "",
      "address5": "",
      "postcode": "SE1 0BJ"
    },
    "code": "C01BL00",
    "courtHearingLocation": "C01BL00",
    "courtLocationCode": "0428",
    "id": "89592405-c29b-3706-b1d3-b1dd3a08b227",
    "lja": {
      "ljaCode": "2570",
      "ljaName": "Central London Magistrates' Court"
    },
    "name": "Blackfriars Crown Court",
    "roomId": "d0624ee3-9198-3c8b-94d6-42fb197ebe5e",
    "roomName": "Courtroom 01"
  },
  "nowContent": {
    "orderDate": "2026-05-20",
    "defendant": {
      "dateOfBirth": "1976-05-19",
      "gender": "MALE",
      "driverNumber": "VANFL002222OW9PH",
      "title": "Mr",
      "firstName": "Delsie",
      "lastName": "Bosco",
      "name": "Delsie Bosco",
      "address": {
        "line1": "33 Bridge Street",
        "line2": "Bridge Street",
        "line3": "Stratford-upon-Avon",
        "line4": "Warwickshire",
        "postCode": "CV37 6AB"
      }
    },
    "caseApplicationReferences": [
      "IS148228747"
    ],
    "cases": [
      {
        "caseStatus": "INACTIVE",
        "initiationCode": "C",
        "reference": "IS148228747",
        "caseId": "9158d3f4-9878-4266-a8a2-4b1d7c80163a",
        "defendantCaseOffences": [
          {
            "title": "Use a motor vehicle on a road / public place without third party insurance",
            "civilOffence": false,
            "dvlaCode": "IN10",
            "convictionDate": "2026-05-19",
            "convictionStatus": "Convicted",
            "plea": "GUILTY",
            "code": "RA88001",
            "modeOfTrial": "Summary",
            "allocationDecision": "Summary-only offence",
            "endorsableFlag": true,
            "convictingCourtCode": "2577",
            "wording": "Use a motor vehicle on a road / public place without third party insurance",
            "startDate": "2026-03-20",
            "results": [
              {
                "resultIdentifier": "554c2622-c1cc-459e-a98d-b7f317ab065c",
                "publishedForNows": false,
                "prompts": [
                  {
                    "promptIdentifier": "d3205319-84cf-4c5b-9d7a-7e4bb1865054",
                    "promptReference": "periodofConditionalDischarge",
                    "durationSequence": 1,
                    "label": "Period of conditional discharge",
                    "value": "10 Months"
                  }
                ],
                "d20": false,
                "dvlaCode": "E",
                "judicialResultCategory": "FINAL",
                "label": "Conditional discharge"
              },
              {
                "resultIdentifier": "f121db73-57fb-4f74-9ab1-0843aabe4605",
                "publishedForNows": false,
                "prompts": [
                  {
                    "promptIdentifier": "dcaf502b-44d2-4be0-acfc-2f7d29142da6",
                    "promptReference": "specialReasons",
                    "label": "Special reasons",
                    "value": "Test"
                  }
                ],
                "d20": false,
                "judicialResultCategory": "ANCILLARY",
                "label": "No endorsement - Special Reasons"
              }
            ]
          },
          {
            "title": "Drive a motor vehicle otherwise than in accordance with a licence - endorsable offence",
            "civilOffence": false,
            "dvlaCode": "LC20",
            "convictionDate": "2026-05-19",
            "convictionStatus": "Convicted",
            "plea": "GUILTY",
            "code": "RT88334",
            "modeOfTrial": "Summary",
            "allocationDecision": "Summary-only offence",
            "endorsableFlag": true,
            "convictingCourtCode": "2577",
            "wording": "Drive a motor vehicle otherwise than in accordance with a licence - endorsable offence",
            "startDate": "2026-03-20",
            "results": [
              {
                "resultIdentifier": "3e859586-bc86-407d-bd8e-c9a01d40d147",
                "publishedForNows": false,
                "d20": false,
                "judicialResultCategory": "FINAL",
                "label": "Offence not dealt with as part of application - original adjudication to stand"
              }
            ]
          },
          {
            "title": "Cause use of motor vehicle with no insurance",
            "civilOffence": false,
            "dvlaCode": "IN14",
            "convictionDate": "2026-05-19",
            "convictionStatus": "Convicted",
            "plea": "GUILTY",
            "code": "RA88002",
            "modeOfTrial": "Summary",
            "allocationDecision": "Summary-only offence",
            "endorsableFlag": true,
            "convictingCourtCode": "2577",
            "wording": "Cause use of motor vehicle with no insurance",
            "startDate": "2026-03-20",
            "results": [
              {
                "resultIdentifier": "3e859586-bc86-407d-bd8e-c9a01d40d147",
                "publishedForNows": false,
                "d20": false,
                "judicialResultCategory": "FINAL",
                "label": "Offence not dealt with as part of application - original adjudication to stand"
              }
            ]
          }
        ]
      }
    ],
    "courtApplications": [
      {
        "applicationType": "Appeal against sentence by a Magistrates' Court to the Crown Court",
        "applicationTypeId": "ef71f385-88f5-4e53-8b9f-d568af9ea90c",
        "applicationReceivedDate": "2026-05-19",
        "id": "de2aa572-1bb1-41cb-9116-5f44143e8060",
        "applicationReference": "IS148228747",
        "applicationStatus": "FINALISED",
        "results": [
          {
            "resultIdentifier": "d861586a-df88-440d-98d4-63cc2a680ae1",
            "publishedForNows": false,
            "prompts": [
              {
                "promptIdentifier": "c946a5df-5849-4cca-b425-ecbd6bd704dc",
                "promptReference": "dateSentenceWasImposed",
                "label": "Date sentence was imposed",
                "value": "19/05/2026"
              },
              {
                "promptIdentifier": "c10b4c83-1856-4ca9-9592-d8b8183a0324",
                "promptReference": "reasons",
                "label": "Reasons",
                "value": "sentence was imposed"
              }
            ],
            "resultWording": "",
            "d20": false,
            "judicialResultCategory": "FINAL",
            "label": "Appeal against sentence allowed"
          }
        ]
      }
    ]
  },
  "isReshare": false,
  "orderingHearingId": "99eb293b-de1c-4398-abc4-dc7dc35af046"
}
